# Generated by Django 2.2.8 on 2021-11-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to='category',
        ),
    ]
