# Generated by Django 2.2.8 on 2021-11-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211130_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['price']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='item',
            order_with_respect_to=None,
        ),
    ]
