# Generated by Django 2.2.8 on 2021-12-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211130_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='states',
            new_name='state',
        ),
    ]
