# Generated by Django 2.2.8 on 2020-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200928_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a random description blahblahblahblah.'),
            preserve_default=False,
        ),
    ]
