# Generated by Django 2.2.8 on 2021-02-16 03:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country_address',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
