# Generated by Django 2.2.8 on 2021-02-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210216_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='city_address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='country_address',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='states_address',
            new_name='states',
        ),
    ]
