# Generated by Django 2.2.8 on 2021-03-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210223_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
