# Generated by Django 2.2.8 on 2021-05-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210414_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
