# Generated by Django 2.2.8 on 2021-11-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
